// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ngDotnetCoreExample.Models.DataModel;

namespace ngDotnetCoreExample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181206053047_InitiateDatabase")]
    partial class InitiateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ngDotnetCoreExample.Domain.AppEvent", b =>
                {
                    b.Property<int>("AppEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppEventDescription");

                    b.Property<string>("AppEventEndDate")
                        .IsRequired();

                    b.Property<string>("AppEventStartDate")
                        .IsRequired();

                    b.Property<string>("AppEventTitle")
                        .IsRequired();

                    b.HasKey("AppEventId");

                    b.ToTable("AppEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
